//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrowseEpub.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrowseEpub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Album 的當地語系化字串。
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Files in the Directory 的當地語系化字串。
        /// </summary>
        public static string AlbumFileList {
            get {
                return ResourceManager.GetString("AlbumFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Info. 的當地語系化字串。
        /// </summary>
        public static string AlbumInfo {
            get {
                return ResourceManager.GetString("AlbumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Analyzing the album EPUB file... 的當地語系化字串。
        /// </summary>
        public static string AnalyzingEpubMsg {
            get {
                return ResourceManager.GetString("AnalyzingEpubMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album EPUB Browser 的當地語系化字串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ascending Order 的當地語系化字串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 at 的當地語系化字串。
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Author: 的當地語系化字串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photo Date (Begin): 的當地語系化字串。
        /// </summary>
        public static string BeginDate {
            get {
                return ResourceManager.GetString("BeginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Browse File 的當地語系化字串。
        /// </summary>
        public static string BrowseFile {
            get {
                return ResourceManager.GetString("BrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please pick an .album.epub file to read.... 的當地語系化字串。
        /// </summary>
        public static string BrowseFileMsg {
            get {
                return ResourceManager.GetString("BrowseFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Author 的當地語系化字串。
        /// </summary>
        public static string ByAuthor {
            get {
                return ResourceManager.GetString("ByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Date 的當地語系化字串。
        /// </summary>
        public static string ByDate {
            get {
                return ResourceManager.GetString("ByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Filename 的當地語系化字串。
        /// </summary>
        public static string ByFilename {
            get {
                return ResourceManager.GetString("ByFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 By Title 的當地語系化字串。
        /// </summary>
        public static string ByTitle {
            get {
                return ResourceManager.GetString("ByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cancel 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chapter 的當地語系化字串。
        /// </summary>
        public static string Chapter {
            get {
                return ResourceManager.GetString("Chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear the cached album data... 的當地語系化字串。
        /// </summary>
        public static string ClearCacheMsg {
            get {
                return ResourceManager.GetString("ClearCacheMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Descending Order 的當地語系化字串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detail View 的當地語系化字串。
        /// </summary>
        public static string DetailViewMode {
            get {
                return ResourceManager.GetString("DetailViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The directory does not exist. 的當地語系化字串。
        /// </summary>
        public static string DirectoryNotExist {
            get {
                return ResourceManager.GetString("DirectoryNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done. 的當地語系化字串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photo Date (End): 的當地語系化字串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select the file name and folder of the exported photo. 的當地語系化字串。
        /// </summary>
        public static string ExportPhotoMsg {
            get {
                return ResourceManager.GetString("ExportPhotoMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The file is exported to 的當地語系化字串。
        /// </summary>
        public static string FileExportedOK {
            get {
                return ResourceManager.GetString("FileExportedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The file does not exist. 的當地語系化字串。
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Find in Albums 的當地語系化字串。
        /// </summary>
        public static string FindInAlbums {
            get {
                return ResourceManager.GetString("FindInAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Found paragraphs: 的當地語系化字串。
        /// </summary>
        public static string FoundParagraphs {
            get {
                return ResourceManager.GetString("FoundParagraphs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.cyberworlds.net/bwsepub/manual_en.php 的當地語系化字串。
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Icon View 的當地語系化字串。
        /// </summary>
        public static string IconViewMode {
            get {
                return ResourceManager.GetString("IconViewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inflate necessary files from the EPUB file... 的當地語系化字串。
        /// </summary>
        public static string InflateFilesMsg {
            get {
                return ResourceManager.GetString("InflateFilesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Photo Location: 的當地語系化字串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 More... 的當地語系化字串。
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next 的當地語系化字串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Nothing is found. 的當地語系化字串。
        /// </summary>
        public static string NoResultMsg {
            get {
                return ResourceManager.GetString("NoResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The file is not an album! 的當地語系化字串。
        /// </summary>
        public static string NotAnAlbumEpub {
            get {
                return ResourceManager.GetString("NotAnAlbumEpub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Online Help 的當地語系化字串。
        /// </summary>
        public static string OnlineHelp {
            get {
                return ResourceManager.GetString("OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paragraph Text: 的當地語系化字串。
        /// </summary>
        public static string ParagraphText {
            get {
                return ResourceManager.GetString("ParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preface 的當地語系化字串。
        /// </summary>
        public static string Preface {
            get {
                return ResourceManager.GetString("Preface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Previous 的當地語系化字串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Read the Album 的當地語系化字串。
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Ready. 的當地語系化字串。
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fetching the album information in the working directory... 的當地語系化字串。
        /// </summary>
        public static string RefreshingMsg {
            get {
                return ResourceManager.GetString("RefreshingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Rotate 的當地語系化字串。
        /// </summary>
        public static string Rotate {
            get {
                return ResourceManager.GetString("Rotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Save As... 的當地語系化字串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please pick the range of photo dates, optionally key in the words to search in fields, then click the search button. 的當地語系化字串。
        /// </summary>
        public static string SearchHintMsg {
            get {
                return ResourceManager.GetString("SearchHintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Searching in the album... 的當地語系化字串。
        /// </summary>
        public static string SearchingInAlbum {
            get {
                return ResourceManager.GetString("SearchingInAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select an album in the list. 的當地語系化字串。
        /// </summary>
        public static string SelectFileMsg {
            get {
                return ResourceManager.GetString("SelectFileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sort 的當地語系化字串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start searching... 的當地語系化字串。
        /// </summary>
        public static string StartSearching {
            get {
                return ResourceManager.GetString("StartSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Title: 的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unknown 的當地語系化字串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The user has cancelled the process. 的當地語系化字串。
        /// </summary>
        public static string UserCancelMsg {
            get {
                return ResourceManager.GetString("UserCancelMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Double click on an album to read it. 的當地語系化字串。
        /// </summary>
        public static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
    }
}
